project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Mingfeng Wang"
  description: "Porous Media, Computational Fluid Dynamic, Continuum Mechanics, Fluid Structure Interaction"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: Publications
        href: publications.qmd
      # - text: Teaching
      #   href: teaching.qmd
      # - text: Outreach
      #   href: outreach.qmd
      # - text: CV
      #   href: curriculum.qmd
    right:
      # - icon: github
      #   href: https://github.com/valegiunchiglia/
      # - icon: twitter
      #   href: https://twitter.com/valegiunca/
      - icon: envelope
        href: "mailto:mingfeng.wang@outlook.com"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    linkcolor: black



